- name: Configure the webserver
  hosts: servers
  become: yes
  become_method: sudo
  tasks:
    - name: Install Httpd
      package:
        name: httpd
        state: present
      ignore_errors: yes

    - name: Copy the index page at document root
      copy:
        src: index.html
        dest: /var/www/html/index.html
      ignore_errors: yes

    - name: start the server
      service:
        name: httpd
        state: started
      ignore_errors: yes

