---

# First, Do all of the provisioning and add the hosts to in-memory inventory
- hosts: all
  gather_facts: true
  connection: local
  vars:
    hostname: "xxxxx"
    username: "xxxx"
    password: "xxxxx"
    datacenter: "xxxx"
    folder: "xxxxx"
    template: "coreos"
    datastore: "xxxxx"
    net_type: "xxxx"
    netmask: "255.255.255.0"
    server_ip: "192.168.1.5"
    gateway: "192.168.1.1"
  tasks:
  - name: "PROVISION | Create VM from template | Network type static"
    vmware_guest:
      validate_certs: "{{ validate_certs }}"
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter }}"
      name: "test-vm-1"
      folder: "{{ folder }}"
      template: "{{ vmtemplate }}"
      state: poweredon
      annotation: '{{ vmnotes|default("Nothing significant to report") }}'
      cluster: "{{ cluster|default('homefarm_cluster') }}"
      hardware:
        num_cpus: "1"
        memory_mb: "8Gi"
      disk:
      - size_gb: "120Gi"
        type: thin
        datastore: "{{ datastore }}"
      networks:
      - name: "testvlan"
        type: "{{ net_type }}"
        ip: "{{ server_ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
      wait_for_ip_address: yes
    register: stat_vm
    when: net_type == 'static'

  - name: "INVENTORY | Update temp inventory with new host"
    add_host:
      hostname: "{{ item.hw_name }}"
      ansible_host: "{{ item.ipv4 }}"
      groups: stage1
    with_items:
      - "{{ stat_vm.instance }}"
